/**
 * Drawing-bar icon registry
 *
 * mapping keys come in two flavours:
 *   1. klinecharts overlay name (e.g. 'horizontalStraightLine') — used as the
 *      overlay `name` passed to klinecharts AND looked up here for the icon.
 *   2. TV icon / control name (e.g. 'cursorGroup', 'ruler') — used only for
 *      group-header buttons and toolbar controls.
 *
 * Every value is the zero-arg arrow function generated by generate-icons.mjs.
 */

import type { FC } from 'react'
import i18n from '../../../i18n'

// ── Group header icons ─────────────────────────────────────────────────────
import cursorGroup    from './cursorGroup'
import trendLineGroup from './trendLineGroup'
import gannFibGroup   from './gannFibGroup'
import patternsGroup  from './patternsGroup'
import predictionGroup from './predictionGroup'
import shapesGroup    from './shapesGroup'
import annotationGroup from './annotationGroup'
import emojiGroup     from './emojiGroup'

// ── Toolbar controls ──────────────────────────────────────────────────────
import magnet      from './magnet'
import strongMagnet from './strongMagnet'
import lockAll     from './lockAll'
import hideAll     from './hideAll'
import trash       from './trash'
import ruler       from './ruler'
import drawingMode from './drawingMode'

// ── Cursor / marker tools ─────────────────────────────────────────────────
import cursorStar  from './cursorStar'
import dotMarker   from './dotMarker'
import arrowMarker from './arrowMarker'
import brushPath   from './brushPath'
import eraser      from './eraser'

// ── Trend / line tools ────────────────────────────────────────────────────
import lineToolHorzLine  from './lineToolHorzLine'
import lineToolHorzRay   from './lineToolHorzRay'
import lineToolVertLine  from './lineToolVertLine'
import lineToolCrossLine from './lineToolCrossLine'
import lineToolExtended  from './lineToolExtended'
import lineToolRay       from './lineToolRay'
import lineToolInfoLine  from './lineToolInfoLine'
import lineToolTrendAngle from './lineToolTrendAngle'
import lineToolParallel  from './lineToolParallel'
import lineToolRegression from './lineToolRegression'
import lineToolFlatBottom from './lineToolFlatBottom'
import lineToolDisjoint  from './lineToolDisjoint'
import lineToolArrow     from './lineToolArrow'
import lineToolArrowUp   from './lineToolArrowUp'
import lineToolArrowDown from './lineToolArrowDown'
import lineToolArrowMark from './lineToolArrowMark'

// ── Fibonacci / Gann ──────────────────────────────────────────────────────
import lineToolFibExtension from './lineToolFibExtension'
import lineToolFibChannel   from './lineToolFibChannel'
import lineToolFibTimeZone  from './lineToolFibTimeZone'
import lineToolFibSRFan     from './lineToolFibSRFan'
import lineToolFibTime      from './lineToolFibTime'
import lineToolFibCircles   from './lineToolFibCircles'
import lineToolFibSpiral    from './lineToolFibSpiral'
import lineToolFibSRArcs    from './lineToolFibSRArcs'
import lineToolFibWedge     from './lineToolFibWedge'
import lineToolPitchfork    from './lineToolPitchfork'
import lineToolSchiff       from './lineToolSchiff'
import lineToolSchiff2      from './lineToolSchiff2'
import lineToolInsidePitch  from './lineToolInsidePitch'
import lineToolPitchfan     from './lineToolPitchfan'
import lineToolGannSquare   from './lineToolGannSquare'
import lineToolGannFixed    from './lineToolGannFixed'
import lineToolGannComplex  from './lineToolGannComplex'
import lineToolGannFan      from './lineToolGannFan'

// ── Chart patterns ────────────────────────────────────────────────────────
import lineToolCypher       from './lineToolCypher'
import lineToolHnS          from './lineToolHnS'
import lineToolABCD         from './lineToolABCD'
import lineToolTrianglePat  from './lineToolTrianglePat'
import lineToolThreeDrivers from './lineToolThreeDrivers'
import lineToolElliottI     from './lineToolElliottI'
import lineToolElliottC     from './lineToolElliottC'
import lineToolElliottT     from './lineToolElliottT'
import lineToolElliottD     from './lineToolElliottD'
import lineToolElliottTr    from './lineToolElliottTr'
import lineToolCircleLines  from './lineToolCircleLines'
import lineToolTimeCycles   from './lineToolTimeCycles'
import lineToolSine         from './lineToolSine'
import lineToolBarsPattern  from './lineToolBarsPattern'
import lineToolGhostFeed    from './lineToolGhostFeed'
import lineToolProjection   from './lineToolProjection'
import lineToolPrediction   from './lineToolPrediction'
import lineToolRiskReward   from './lineToolRiskReward'
import lineToolVWAP         from './lineToolVWAP'
import lineToolFixedVol     from './lineToolFixedVol'
import lineToolAnchorVol    from './lineToolAnchorVol'
import lineToolPriceRange   from './lineToolPriceRange'
import lineToolDateRange    from './lineToolDateRange'
import lineToolDatePrice    from './lineToolDatePrice'

// ── Geometric shapes ──────────────────────────────────────────────────────
import lineToolRect        from './lineToolRect'
import lineToolRotRect     from './lineToolRotRect'
import lineToolCircle      from './lineToolCircle'
import lineToolEllipse     from './lineToolEllipse'
import lineToolTriangle    from './lineToolTriangle'
import lineToolArc         from './lineToolArc'
import lineToolPolyline    from './lineToolPolyline'
import lineToolPath        from './lineToolPath'
import lineToolBezierQ     from './lineToolBezierQ'
import lineToolBezierC     from './lineToolBezierC'
import lineToolHighlighter from './lineToolHighlighter'

// ── Annotations / labels ──────────────────────────────────────────────────
import lineToolText       from './lineToolText'
import lineToolTextNote   from './lineToolTextNote'
import lineToolPriceNote  from './lineToolPriceNote'
import lineToolNote       from './lineToolNote'
import lineToolCallout    from './lineToolCallout'
import lineToolComment    from './lineToolComment'
import lineToolPriceLabel from './lineToolPriceLabel'
import lineToolSignpost   from './lineToolSignpost'
import lineToolFlag       from './lineToolFlag'
import lineToolTable      from './lineToolTable'
import lineToolImage      from './lineToolImage'
import lineToolTweet      from './lineToolTweet'
import lineToolIdea       from './lineToolIdea'

// ---------------------------------------------------------------------------
// Icon mapping
// ---------------------------------------------------------------------------
export const mapping: Record<string, () => any> = {
  // ── Group headers ──────────────────────────────────────────────────────
  cursorGroup,
  trendLineGroup,
  gannFibGroup,
  predictionGroup,
  patternsGroup,
  shapesGroup,
  annotationGroup,
  emojiGroup,

  // ── Controls ──────────────────────────────────────────────────────────
  ruler,
  drawingMode,
  lockAll,
  hideAll,
  trash,
  // legacy name aliases
  lock:      lockAll,
  unlock:    lockAll,
  remove:    trash,
  removeAll: trash,
  visible:   hideAll,
  invisible: hideAll,
  weak_magnet:   magnet,
  strong_magnet: strongMagnet,

  // ── Cursor / marker tools ─────────────────────────────────────────────
  cursor:      cursorStar,
  dotMarker,
  arrowMarker,
  brushPath,
  eraser,

  // ── klinecharts overlay name → TV icon ────────────────────────────────

  // Horizontal / vertical lines
  horizontalStraightLine: lineToolHorzLine,
  horizontalRayLine:      lineToolHorzRay,
  horizontalSegment:      lineToolHorzLine,   // no segment icon — reuse horzLine
  verticalStraightLine:   lineToolVertLine,
  verticalRayLine:        lineToolVertLine,
  verticalSegment:        lineToolVertLine,

  // Extended / ray / segment
  straightLine:  lineToolExtended,
  rayLine:       lineToolRay,
  segment:       lineToolRay,                 // reuse ray

  // Arrow / freehand / price
  arrow:  lineToolArrow,
  brush:  brushPath,
  priceLine: lineToolHorzLine,               // price line ≈ horizontal

  // Channels / parallel
  priceChannelLine:     lineToolParallel,
  parallelStraightLine: lineToolParallel,

  // Fibonacci
  fibonacciLine:               lineToolFibChannel,
  fibonacciSegment:            lineToolFibExtension,
  fibonacciCircle:             lineToolFibCircles,
  fibonacciSpiral:             lineToolFibSpiral,
  fibonacciSpeedResistanceFan: lineToolFibSRFan,
  fibonacciExtension:          lineToolFibExtension,

  // Gann
  gannBox: lineToolGannSquare,

  // Elliott / waves
  xabcd:      lineToolCypher,
  abcd:       lineToolABCD,
  threeWaves: lineToolElliottI,
  fiveWaves:  lineToolElliottC,
  eightWaves: lineToolElliottD,
  anyWaves:   lineToolElliottTr,

  // Shapes
  circle:       lineToolCircle,
  rect:         lineToolRect,
  triangle:     lineToolTriangle,
  parallelogram: lineToolRotRect,

  // Fibonacci / Gann / Pitchfork tools (extended)
  lineToolFibTimeZone,
  lineToolFibTime,
  lineToolFibSRArcs,
  lineToolFibWedge,
  lineToolPitchfork,
  lineToolSchiff,
  lineToolSchiff2,
  lineToolInsidePitch,
  lineToolPitchfan,
  lineToolGannFixed,
  lineToolGannComplex,
  lineToolGannFan,

  // Trendline tools (extended)
  lineToolTrendAngle,
  lineToolCrossLine,
  lineToolDisjoint,
  lineToolFlatBottom,
  lineToolInfoLine,
  lineToolRegression,
  lineToolArrowUp,
  lineToolArrowDown,
  lineToolArrowMark,

  // Chart patterns / Elliott
  lineToolHnS,
  lineToolTrianglePat,
  lineToolThreeDrivers,
  lineToolElliottT,
  lineToolCircleLines,
  lineToolTimeCycles,

  // Prediction / measurement / misc tools
  lineToolSine,
  lineToolBarsPattern,
  lineToolGhostFeed,
  lineToolProjection,
  lineToolPrediction,
  lineToolRiskReward,
  lineToolVWAP,
  lineToolFixedVol,
  lineToolAnchorVol,
  lineToolPriceRange,
  lineToolDateRange,
  lineToolDatePrice,

  // Geometric shapes (extended)
  lineToolEllipse,
  lineToolArc,
  lineToolPolyline,
  lineToolPath,
  lineToolBezierQ,
  lineToolBezierC,
  lineToolHighlighter,

  // Annotations / labels
  lineToolText,
  lineToolTextNote,
  lineToolPriceNote,
  lineToolNote,
  lineToolCallout,
  lineToolComment,
  lineToolPriceLabel,
  lineToolSignpost,
  lineToolFlag,
  lineToolTable,
  lineToolImage,
  lineToolTweet,
  lineToolIdea,
}

// ---------------------------------------------------------------------------
// DrawingToolItem — extended SelectDataSourceItem for the drawing bar groups.
// ---------------------------------------------------------------------------
export interface DrawingToolItem {
  /** klinecharts overlay name to create — OR 'cursor'/'eraser' for mode changes */
  key: string
  /** Icon name override. Falls back to `key` if omitted. */
  iconKey?: string
  /** Display label */
  text: string
  /** true → resets to cursor/crosshair mode (no overlay created) */
  isCursorMode?: boolean
  /** true → toggles eraser/delete mode (no overlay created) */
  isEraserMode?: boolean
  /** Data passed to the overlay's extendData (e.g. emoji text for simpleAnnotation) */
  extendData?: unknown
}

// ---------------------------------------------------------------------------
// Group factory functions
// ---------------------------------------------------------------------------

/** Group 1 — Cursor / pointer tools */
export function createCursorOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'cursor',      iconKey: 'cursor',      text: i18n('cursor', locale),      isCursorMode: true },
    { key: 'circle',      iconKey: 'dotMarker',   text: i18n('dot', locale) },
    { key: 'arrow',       iconKey: 'arrowMarker', text: i18n('arrow', locale) },
    { key: 'brush',       iconKey: 'brushPath',   text: i18n('brush', locale) },
    { key: 'eraser',      iconKey: 'eraser',      text: i18n('eraser', locale),      isEraserMode: true },
  ]
}

/** Group 2 — Trend / line tools */
export function createTrendlineOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'horizontalStraightLine', text: i18n('horizontal_straight_line', locale) },
    { key: 'horizontalRayLine',      text: i18n('horizontal_ray_line', locale) },
    { key: 'horizontalSegment',      iconKey: 'horizontalStraightLine', text: i18n('horizontal_segment', locale) },
    { key: 'verticalStraightLine',   text: i18n('vertical_straight_line', locale) },
    { key: 'verticalRayLine',        iconKey: 'verticalStraightLine', text: i18n('vertical_ray_line', locale) },
    { key: 'verticalSegment',        iconKey: 'verticalStraightLine', text: i18n('vertical_segment', locale) },
    { key: 'straightLine',           text: i18n('straight_line', locale) },
    { key: 'rayLine',                text: i18n('ray_line', locale) },
    { key: 'segment',                iconKey: 'rayLine', text: i18n('segment', locale) },
    { key: 'arrow',                  text: i18n('arrow', locale) },
    { key: 'priceLine',              iconKey: 'horizontalStraightLine', text: i18n('price_line', locale) },
    { key: 'brush',                  iconKey: 'brushPath', text: i18n('brush', locale) },
    { key: 'priceChannelLine',       text: i18n('price_channel_line', locale) },
    { key: 'parallelStraightLine',   iconKey: 'priceChannelLine', text: i18n('parallel_straight_line', locale) },
  ]
}

/** Group 3 — Gann & Fibonacci tools */
export function createGannFibOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'fibonacciLine',               iconKey: 'fibonacciLine',    text: i18n('fibonacci_line', locale) },
    { key: 'fibonacciSegment',            iconKey: 'fibonacciSegment', text: i18n('fibonacci_segment', locale) },
    { key: 'fibonacciCircle',             iconKey: 'fibonacciCircle',  text: i18n('fibonacci_circle', locale) },
    { key: 'fibonacciSpiral',             iconKey: 'fibonacciSpiral',  text: i18n('fibonacci_spiral', locale) },
    { key: 'fibonacciSpeedResistanceFan', iconKey: 'fibonacciSpeedResistanceFan', text: i18n('fibonacci_speed_resistance_fan', locale) },
    { key: 'fibonacciExtension',          iconKey: 'fibonacciExtension', text: i18n('fibonacci_extension', locale) },
    { key: 'gannBox',                     iconKey: 'gannBox', text: i18n('gann_box', locale) },
    // Pitchfork tools — klinecharts uses 'straightLine' as fallback until native support
    { key: 'straightLine', iconKey: 'lineToolPitchfork',   text: 'Andrews Pitchfork' },
    { key: 'straightLine', iconKey: 'lineToolSchiff',      text: 'Schiff Pitchfork' },
    { key: 'straightLine', iconKey: 'lineToolGannFan',     text: 'Gann Fan' },
    { key: 'straightLine', iconKey: 'lineToolGannSquare',  text: 'Gann Square' },
    { key: 'straightLine', iconKey: 'lineToolGannFixed',   text: 'Gann Box (Fixed)' },
  ]
}

/** Group 4 — Chart patterns */
export function createPatternOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'xabcd',      iconKey: 'xabcd',      text: i18n('xabcd', locale) },
    { key: 'abcd',       iconKey: 'abcd',        text: i18n('abcd', locale) },
    { key: 'threeWaves', iconKey: 'threeWaves',  text: i18n('three_waves', locale) },
    { key: 'fiveWaves',  iconKey: 'fiveWaves',   text: i18n('five_waves', locale) },
    { key: 'eightWaves', iconKey: 'eightWaves',  text: i18n('eight_waves', locale) },
    { key: 'anyWaves',   iconKey: 'anyWaves',    text: i18n('any_waves', locale) },
    // Additional TV patterns — fallback to straight line until native klinecharts support
    { key: 'straightLine', iconKey: 'lineToolHnS',         text: 'Head & Shoulders' },
    { key: 'straightLine', iconKey: 'lineToolTrianglePat', text: 'Triangle Pattern' },
    { key: 'straightLine', iconKey: 'lineToolThreeDrivers', text: 'Three Drives' },
    { key: 'straightLine', iconKey: 'lineToolCypher',       text: 'Cypher Pattern' },
  ]
}

/** Group 5 — Geometric shapes */
export function createShapeOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'circle',       iconKey: 'circle',       text: i18n('circle', locale) },
    { key: 'rect',         iconKey: 'rect',          text: i18n('rect', locale) },
    { key: 'triangle',     iconKey: 'triangle',      text: i18n('triangle', locale) },
    { key: 'parallelogram', iconKey: 'parallelogram', text: i18n('parallelogram', locale) },
    // TV shapes — fallback to circle until native klinecharts support
    { key: 'circle', iconKey: 'lineToolEllipse',     text: 'Ellipse' },
    { key: 'circle', iconKey: 'lineToolArc',         text: 'Arc' },
    { key: 'circle', iconKey: 'lineToolPolyline',    text: 'Polyline' },
    { key: 'circle', iconKey: 'lineToolBezierQ',     text: 'Curve (Quadratic)' },
    { key: 'circle', iconKey: 'lineToolBezierC',     text: 'Curve (Cubic)' },
    { key: 'circle', iconKey: 'lineToolHighlighter', text: 'Highlighter' },
  ]
}

/** Group 6 — Annotation / text tools */
export function createAnnotationOptions(_locale: string): DrawingToolItem[] {
  return [
    // All annotation tools fall back to 'horizontalStraightLine' until
    // klinecharts adds native text-overlay support.
    { key: 'horizontalStraightLine', iconKey: 'lineToolText',       text: 'Text' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolNote',        text: 'Note' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolTextNote',    text: 'Text Note' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolCallout',     text: 'Callout' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolComment',     text: 'Comment' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolPriceNote',   text: 'Price Note' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolPriceLabel',  text: 'Price Label' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolSignpost',    text: 'Signpost' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolFlag',        text: 'Flag' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolTable',       text: 'Table' },
    { key: 'horizontalStraightLine', iconKey: 'lineToolImage',       text: 'Image' },
  ]
}

/** Group 7 — Emoji / icon markers drawn via emojiMarker overlay */
export function createEmojiOptions(_locale: string): DrawingToolItem[] {
  return [
    { key: 'emojiMarker', text: '👍 Thumbs Up',   extendData: { text: '👍' } },
    { key: 'emojiMarker', text: '👎 Thumbs Down',  extendData: { text: '👎' } },
    { key: 'emojiMarker', text: '⭐ Star',         extendData: { text: '⭐' } },
    { key: 'emojiMarker', text: '❤️ Heart',        extendData: { text: '❤️' } },
    { key: 'emojiMarker', text: '💡 Idea',         extendData: { text: '💡' } },
    { key: 'emojiMarker', text: '⚠️ Warning',      extendData: { text: '⚠️' } },
    { key: 'emojiMarker', text: '🚀 Rocket',       extendData: { text: '🚀' } },
    { key: 'emojiMarker', text: '🔥 Fire',         extendData: { text: '🔥' } },
  ]
}

/** Magnet mode selector */
export function createMagnetOptions(locale: string): DrawingToolItem[] {
  return [
    { key: 'weak_magnet',   iconKey: 'weak_magnet',   text: i18n('weak_magnet', locale) },
    { key: 'strong_magnet', iconKey: 'strong_magnet', text: i18n('strong_magnet', locale) },
  ]
}

/** Hide-all dropdown — text-only items (no overlay created) */
export function createHideAllOptions(_locale: string): DrawingToolItem[] {
  return [
    { key: 'show_all', text: 'Show All Drawings' },
    { key: 'hide_all', text: 'Hide All Drawings' },
    { key: 'show_labels', text: 'Show All Labels' },
    { key: 'hide_labels', text: 'Hide All Labels' },
  ]
}

// ---------------------------------------------------------------------------
// Icon component
// ---------------------------------------------------------------------------
interface IconProps {
  /** Icon name — a key in `mapping`. Falls back to nothing if not found. */
  name: string
  className?: string
}

export const Icon: FC<IconProps> = ({ name }) => {
  const IconFn = mapping[name] as (() => any) | undefined
  return IconFn ? IconFn() : null
}
